global:
  scrape_interval: 15s # Scrape metrics every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds


scrape_configs:
  # Scrape metrics from application
  - job_name: 'go-microservice'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
